### ISSUE TITLE
Ошибка при первичной настройке

### ISSUE THREAD

**Issue by spawnax** [alryaz/hass-turkov#1]
Привет!
Ввожу локальный IP установки, а визард мне ругается "Cannot connect to host"

**Comment by alryaz** [comment]
Здравствуйте!

Напишите, пожалуйста, в Telegram: http://t.me/alryaz

Компонент оттачивался на Capsule; есть возможность, что АПИ немного отличается.

**Comment by alryaz** [comment]
Исправлено в v2023.6.2
